### ISSUE TITLE
Wrong network time when app returns from background

### ISSUE THREAD

**Issue by jebadiah** [jbenet/ios-ntp#1]
When I put the app in background, change the time from settings and then go back to the application, it seems that it is returning the wrong network time. Do you have any work around for this? Thank you very much in advance.

**Comment by adamn** [comment]
I just tried this and it now works (or those steps aren't sufficient to reproduce).  So much code has changed that I suggest this ticket be closed.  It can always be reopened.

**Comment by gavineadie** [comment]
Agreed.
