### ISSUE TITLE
Method override for the designed initializer not found

### ISSUE THREAD

**Issue by lunarbase** [jbenet/ios-ntp#33]
I see this error on NetAssociation.m: 

...Pods/ios-ntp/ios-ntp-lib/NetAssociation.m:116:17: Method override for the designated initializer of the superclass '-init' not found

on Xcode 7.2, iOS 9.2.

**Comment by gavineadie** [comment]
it needs:

    - (instancetype) init NS_UNAVAILABLE;

in NetAssociation.h
