### ISSUE TITLE
Problem with iOS 9.3 beta

### ISSUE THREAD

**Issue by gavineadie** [jbenet/ios-ntp#36]
`ios-ntp` is not performing correctly with the iOS 9.3 public beta.

**Comment by tspent** [comment]
what problem are you dealing?

**Comment by gavineadie** [comment]
I don't know what the cause is, but all the associations become invalid quite quickly.  The software won't let the number of associations drop below eight, but even those eight are invalidated over and over again.  There may be networking changes that impact `CocoaAsyncSocket` so I'll check any new code over there later today.

**Comment by warpling** [comment]
:( Any luck @gavineadie?

**Comment by gavineadie** [comment]
The cause is that the iOS clock is already so close to true time that the small variations in any association's sampling actually have a relatively small average and large standard deviation.  For example, three samples, in microseconds are: 8.8, -3.5 and -1.6 which gives an average of 1.2 mSec within a SD of 5.4 mSec.

The association rejection criteria include requiring that the SD of samples be small compared to the average .. you can see this make sense if the clock time is not accurate (more than, say, ~20 mSec off true), but it breaks down if the clock is already accurate.

This library has lost its value as iOS has matured!  iOS now uses NTP internally, so it keeps good time.  This library is still useful for detecting a deliberate manual resetting of time to an incorrect value for nefarious purposes (which, I suspect, is its main use anyway).

**Comment by bassrock** [comment]
@gavineadie It's also still useful to track time to some internal NTP server that gets a time value from something else. i.e. the space industry.

**Comment by warpling** [comment]
@gavineadie Interesting! I had no idea. I'm one of those people using `NetAssociation` it to prevent clock manipulation ;) Does iOS expose that NTP time (before it's offset by the user) anywhere?

**Comment by gavineadie** [comment]
@bassrock .. NTP could certainly be used to distribute time from private servers slaved to extraordinary sources, perhaps for simulations in which multiple computer need to behave as if they were operating in the past or the future.

@warpling .. no, iOS does not reveal anything about how time is derived and maintained.  I've lobbied Apple for a "CoreTime" framework like "CoreLocation" without success (I believe a CoreTime framework does exist but is private to Apple with unknown functionality).  Such a framework, if public, could reveal deviation from true time, accuracy and source (phone company, GPS, NTP, user setting, etc).

**Comment by warpling** [comment]
@gavineadie Thanks for lobbying Apple ;) And thanks again for all your work on this library.
