### ISSUE TITLE
Crash when returning from background after loss of network connection

### ISSUE THREAD

**Issue by vandutran** [jbenet/ios-ntp#4]
I experienced a crash when returning from background after a network connection loss.

Steps to reproduce:

1. Make sure you have an internet connection
2. Open the app (wait 30 seconds)
3. Close the app (put it in background mode)
4. Turn off internet connection (turn off data or go to airplane mode)
5. Reopen the app
6. It will crash

Thanks.

**Comment by adamn** [comment]
I just tried this and it now works (or those steps aren't sufficient to reproduce).  So much code has changed that I suggest this ticket be closed.  It can always be reopened.

**Comment by gavineadie** [comment]
Agreed.
