### ISSUE TITLE
Can't compile static library

### ISSUE THREAD

**Issue by komocode** [jbenet/ios-ntp#5]
Trying to compile target ios-ntp -> iPhone 6.1 simulator
Getting: 
lipo: can't open input file: /Users/me/Library/Developer/Xcode/DerivedData/ios-ntp-dugtdxdmajqvrpbzrxshalcsxzng/Build/Products/Debug-iphoneos/ios-ntp.framework/ios-ntp (No such file or directory)

**Comment by adamn** [comment]
This doesn't appear to be an issue anymore and I think the issue can be closed.  ios-ntp no longer exists (ios-lib now I believe).  It builds fine for me on Xcode 6.3.2.

**Comment by gavineadie** [comment]
Agreed.
