### ISSUE TITLE
Any update for cocoapod, version is still 1.1.1

### ISSUE THREAD

**Issue by fvisticot** [jbenet/ios-ntp#56]

**Comment by gavineadie** [comment]
I thought I'd updated from v1.1.5 to v1.1.6 a couple of days but missed one reference (I'm not a CocoaPods user), so apologies.  I also updated the copyright date and the plist version.  If I'm still missing something, please let me know, explicitly, what to change/correct ..

**Comment by gavineadie** [comment]
Resolved at v1.1.7
