### ISSUE TITLE
NetAssociation doesn't post any notification

### ISSUE THREAD

**Issue by rzolin** [jbenet/ios-ntp#7]
This was working fine for some time, but then something changed. I traced the calls and every call of [NetAssociation evaluatePacket] the good = 0, fail = 1, unused = 7. And it skips the assoc-fail/good notification part.

I was wondering what could affect it? Could there be a flag in the Build Settings? The code is part of a library, which hasn't been changed. But it stopped working. By the way, I tried different NTP servers and nothing helps.

I would really appreciate the help.

**Comment by adamn** [comment]
This seems like an old dead issue and the code has changed alot.  Suggesting we close.

**Comment by gavineadie** [comment]
Agreed.
